pluginManagement {
    repositories {
        maven { url = "https://maven.fabricmc.net/" }
        maven { url = "https://maven.architectury.dev/" }
        maven { url = "https://maven.minecraftforge.net/" }
        maven { url = "https://maven.parchmentmc.org" }
        maven { url = "https://maven.blamejared.com/" }
        maven { url = "https://maven.gtceu.com" }
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = "jecaex"
